Repository zammad/zammad-documentation, pull requests merged in 2021-03, with the labels that each got.

#166 Update docker-compose.rst
  install/docker-compose.rst
Labels: BLOCKED

#169 Rework and enhance search index attributes
  install/elasticsearch/indexed-attributes.rst
Labels: enhancement, next release

#171 Update Elasticsearch Dependencies, possible packages and Zammad requirements
  install/elasticsearch.rst
  prerequisites/software.rst
Labels: next release
