Repository zammad/zammad-documentation, pull requests merged in 2023-01, with the labels that each got.

#260 Correct paths from sites-enabled to sites-available
  getting-started/configure-webserver.rst
Labels: needs verification

#272 Include a hint that Redis will be a regulard dependency from Zammad 6.0 onwards.
  prerequisites/software.rst
Labels: next release

#273 DRAFT v5.4: Fixes #4437 - DataPrivacy tasks never are cleaned up.
  appendix/privacy.rst
Labels: next release, BLOCKED
